// <auto-generated />
using BookingRooms.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingRooms.API.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20251120021844_CreateEquipmentTable")]
    partial class CreateEquipmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("BookingRooms.API.Features.Equipments.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whiteboard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Conference Phone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
